### ISSUE TITLE
clash订阅节点问题

### ISSUE THREAD

**Issue by wwjj999** [cmliu/edgetunnel#12]
完全使用原版pg方式，订阅未使用任何第三方转换，客户端也未转换，但是clash里的自动选择只有四项地区，而实际可选地区确有多项。那么自动选择就选不到其他的了？故障转移也一样。如图：
![Screenshot_20240310_005004](https://github.com/cmliu/edgetunnel/assets/80992927/e5ceb1eb-08af-441d-9408-714cfa059482)
![Screenshot_20240310_004958](https://github.com/cmliu/edgetunnel/assets/80992927/fc22068c-8263-4214-8646-b0f5c582ec8a)
所以能不能把故障转移和自动选择加上所有地区项？？拜托了

**Comment by cmliu** [comment]
部分地区并不能保证节点充足, 当没有节点的时候会导致直连. 而且你为什么不直接改一下转换配置呢?
