### ISSUE TITLE
期待适配surge

### ISSUE THREAD

**Issue by chptnt** [cmliu/edgetunnel#123]
大佬，我专门买了mac版的surge，就因为看中了它的增强模式，很多软件打开走代理需要增强模式，普通的系统代理不起作用，期待可以适配surge订阅，感谢

**Comment by liao-hao** [comment]
这个可以surgehttps://github.com/cmliu/epeius

**Comment by chptnt** [comment]
兄弟，这个看起来不错，但是 surge 需要挂靠域名才能订阅，有没有免费注册可以挂靠cf的域名介绍一下的？

**Comment by chptnt** [comment]
> 这个可以surgehttps://github.com/cmliu/epeius

感谢兄弟，太牛了，已经实现，但是感觉速度没有edgetunnel 这个优选 IP 快，看视频简介还有下半场，但是没有找到进一步折腾的学习链接，不过已经很快了，再次感谢

**Comment by liao-hao** [comment]
> > 这个可以surgehttps://github.com/cmliu/epeius
> 
> 感谢兄弟，太牛了，已经实现，但是感觉速度没有edgetunnel 这个优选 IP 快，看视频简介还有下半场，但是没有找到进一步折腾的学习链接，不过已经很快了，再次感谢

自己搭的好像和他分享出来的没啥区别啊
