### ISSUE TITLE
通过判断User Agent是否包含Mozilla来判断是否为浏览器访问不准确

### ISSUE THREAD

**Issue by wzwtt** [cmliu/edgetunnel#15]
https://github.com/cmliu/edgetunnel/blob/614829391bba043707ec5aae6e06b8d1a147318e/_worker.js#L878-L881
Shadowrocket小火箭的订阅ua为
````
Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/604.1
````
与相同iOS版本的Safari浏览器相同，因而小火箭无法获取到订阅内容。

建议订阅内容页面与信息展示页面分开，直接通过`url.pathname`判断是需要信息展示页面还是订阅内容。
需修改内容如下：
https://github.com/cmliu/edgetunnel/blob/614829391bba043707ec5aae6e06b8d1a147318e/_worker.js#L65-L95

**Comment by wzwtt** [comment]
我可以发个PR改一下。

**Comment by wzwtt** [comment]
> ![image](https://github.com/cmliu/edgetunnel/assets/24787744/15b2e610-e71a-406c-bc46-8daa65cc1c25)
> 
> 我这边采集到的小火箭UA是这样的啊

我是手机上的小火箭，开stream抓包，然后在小火箭上更新订阅。stream抓包的结果就是这个UA。
![image](https://github.com/cmliu/edgetunnel/assets/21050445/bbea3eac-744b-4d41-ae8d-b76403efc5c4)

**Comment by cmliu** [comment]
![image](https://github.com/cmliu/edgetunnel/assets/24787744/f8f2d137-8dc9-4cc5-baa3-562d6603d82e)
这是我升级到最新版本的UA, 太奇怪了, 要不我加个排除iphone的判断吧,让iphone直接返回b64订阅内容

**Comment by wzwtt** [comment]
破案了。
小火箭为了保护用户隐私，在设置-用户代理-隐藏我的用户代理字符串中默认开启了。
![image](https://github.com/cmliu/edgetunnel/assets/21050445/29902e15-1619-43d0-9a30-046724c14ee3)
开启该功能后，小火箭将用Safari浏览器的UA来代替自己的UA，防止某些机场统计用户使用了何种客户端。
关闭后，Stream抓包即可在UA中显示出小火箭的特征。
应当在README中提醒用户此注意点，并告知相应的隐私风险，因为有些用户可能使用的不止是edgetunnel，还有其他机场。
