### ISSUE TITLE
订阅突然获取节点数变为0

### ISSUE THREAD

**Issue by Asnebula** [cmliu/edgetunnel#154]
一直都好好的，今天更新订阅突然不行，查看日志如下
loading from : https://[qianzhui.yuming]/[uuid]

handle url: https://[qianzhui.yuming]/[uuid]

need remove?: old=0 - new=0

以前都可以订阅到很多节点，现在是old-new=0，求解答

**Comment by carolusliu** [comment]
我的也是，估计是提供订阅的服务挂了吧！

**Comment by entheosl** [comment]
更新订阅失败说是没有获取到可用配置文件

**Comment by Flintzz** [comment]
把最新的worker重新部署一下就行了

**Comment by Asnebula** [comment]
> 把最新的worker重新部署一下就行了

确实更新部署一下就可以了，感谢
