### ISSUE TITLE
没反应了，能连接但是打不开Google

### ISSUE THREAD

**Issue by TheGuessingGuesser** [cmliu/edgetunnel#156]
今天想要登录Google发现打不开网页，但是能加载出Google的图标以及网站标题

**Comment by entheosl** [comment]
那是缓存

**Comment by TheGuessingGuesser** [comment]
> 那是缓存

那请问有什么解决办法吗？Pages今早更新了worker.zip

**Comment by entheosl** [comment]
重新部署也没用吗？

**Comment by TheGuessingGuesser** [comment]
> 重新部署也没用吗？

是的 需不需要换域名或者换uuid？

**Comment by TheGuessingGuesser** [comment]
还有一个比较诡异的，就是singbox选择Global（应该是全局吧）结果国内网站确实秒开，但是非国内网仍然打不开
