### ISSUE TITLE
订阅失效了

### ISSUE THREAD

**Issue by zyrubber** [cmliu/edgetunnel#158]
v2rayN订阅突然失效了，得到一个json文件
`Error fetching content: atob() called with invalid base64-encoded data. (Only whitespace, '+', '/', alphanumeric ASCII, and up to two terminal '=' signs when the input data length is divisible by 4 are allowed.)`

**Comment by MuYoungx** [comment]
我也是

**Comment by zyrubber** [comment]
感谢TG大佬指点。是IP库崩了。换IP库吧。就是更换SUB变量。已经修复

**Comment by MuYoungx** [comment]
> 感谢TG大佬指点。是IP库崩了。换IP库吧。就是更换SUB变量。已经修复

什么意思 怎么操作
