### ISSUE TITLE
更新订阅失败

### ISSUE THREAD

**Issue by nobt854** [cmliu/edgetunnel#19]
Error fetching content: atob() called with invalid base64-encoded data. (Only whitespace, '+', '/', alphanumeric ASCII, and up to two terminal '=' signs when the input data length is divisible by 4 are allowed.)

**Comment by Y4er** [comment]
这是因为 https://sub.cmliussss.workers.dev/ 被速率限制了

<img width="1370" alt="image" src="https://github.com/cmliu/edgetunnel/assets/40487319/66e404ff-ac0e-4556-8d05-275351662f68">

**Comment by nobt854** [comment]
> 这是因为 https://sub.cmliussss.workers.dev/ 被速率限制了
> 
> <img alt="image" width="1370" src="https://private-user-images.githubusercontent.com/40487319/313607086-66e404ff-ac0e-4556-8d05-275351662f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTI1NDAsIm5iZiI6MTcxMDc1MjI0MCwicGF0aCI6Ii80MDQ4NzMxOS8zMTM2MDcwODYtNjZlNDA0ZmYtYWMwZS00NTU2LThkMDUtMjc1MzUxNjYyZjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA4NTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3M2Y2OTE2N2E3MzQ2NDgxMzgzMmYzODBjNzFjZDUxODA3NzM1OTQwNDQ4MzQ3YTRlOTk1ZGU5OWRiNzc2YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dAeYt3JuV1Q9PUFs-YdC5oYwFWDxWy9rehx9MkusIPM">

谢谢解答，请问只能等待吗？

**Comment by yisan** [comment]
用了一会 就不行了，更新订阅报错：
fail: no found ss://, ssr://, vmess://, vless://, trojan://
url: Error fetching content: atob() called with invalid base64-encoded data. (Only whitespace, '+', '/', alphanumeric ASCII, and up to two terminal '=' signs when the input data length is divisible by 4 are allowed.)

**Comment by nobt854** [comment]
sub更新订阅的地址变化了，从源码中下载最新worker.zip重新添加站点部署一次即可
