### ISSUE TITLE
小火箭问题

### ISSUE THREAD

**Issue by AomoDa** [cmliu/edgetunnel#20]
订阅能打开，也能显示延迟，但是连不上网是啥原因？应如何解决，谢谢

**Comment by kxdn3** [comment]
passwall怎么用？连不上

**Comment by fwqaaq** [comment]
不要部署在 worker 上，记得部署到 pages

> 订阅能打开，也能显示延迟，但是连不上网是啥原因？应如何解决，谢谢

**Comment by jo3yzhu** [comment]
> 不要部署在 worker 上，记得部署到 pages
> 
> > 订阅能打开，也能显示延迟，但是连不上网是啥原因？应如何解决，谢谢

同问，已经部署在pages上，且也可以通过小火箭看到延迟，但上网失败

**Comment by fwqaaq** [comment]
>同问，已经部署在pages上，且也可以通过小火箭看到延迟，但上网失败

可以的，应该是节点或者操作问题

**Comment by jo3yzhu** [comment]
> > 同问，已经部署在pages上，且也可以通过小火箭看到延迟，但上网失败
> 
> 可以的，应该是节点或者操作问题

解决了，用macos自带的uuidgen命令生成的uuid无法使用，从网上找了uuid4格式的生成器就成功了。

**Comment by cmliu** [comment]
> passwall怎么用？ 连不上

passwall订阅下面有个UA, 把开头的Mozilla 删掉就可以订阅了

**Comment by AomoDa** [comment]
重新部署就解决了，也不知道啥原因。速度还不错；

可能是uuid的问题，换了个uuid生成器
