### ISSUE TITLE
更新订阅有问题

### ISSUE THREAD

**Issue by qgdlantern** [cmliu/edgetunnel#21]
1、更新订阅完结果如下图：
<img width="461" alt="更新订阅结束" src="https://github.com/cmliu/edgetunnel/assets/3644506/c6c74023-7708-439d-892b-47cf99cff988">
2、更新完所有节点都没了，结果如下图：
<img width="656" alt="结果没了" src="https://github.com/cmliu/edgetunnel/assets/3644506/5ba81647-6b8f-47d8-9fa1-e4ca834c36c9">

**Comment by funkpopo** [comment]
下载最新的worker压缩包即可

**Comment by httpsColon** [comment]
添加变量 SUB = vless-4ca.pages.dev 然后重试部署

**Comment by jeffery9** [comment]
好了，可以解析了。 有这个架构的说明吗，谢谢。

**Comment by jeffery9** [comment]
能订阅，但是 速度 是 -1.

**Comment by CYuSir** [comment]
怎么解？

**Comment by cmliu** [comment]
A：默认内置 sub.cmliussss.workers.dev 订阅器被攻击打死了，旧的代码默认内置订阅器已无法更新节点！
解决方法有三种：
- 1. 去项目 (https://github.com/cmliu/edgetunnel)里用新的代码再部署一次，新的代码更换了内置订阅器；
- 2. 给节点添加变量 SUB = vless-4ca.pages.dev；>视频教程 (https://www.youtube.com/watch?v=s91zjpw3-P8&t=1193s)
- 3. 使用置顶 (https://t.me/CMLiussss/27326)里的自定义订阅的方式订阅。>视频教程 (https://www.youtube.com/watch?v=OjqCKeEY7DQ&t=174s)
