### ISSUE TITLE
正常使用一天后，突然无法获取订阅节点

### ISSUE THREAD

**Issue by yunkai-c** [cmliu/edgetunnel#24]
各个软件均无法获取节点。浏览器输入url可以正常显示内容。

**Comment by imwyh** [comment]
+1,蹲个后续，我还以为我配置文件挂了

**Comment by SSNQ** [comment]
+1

**Comment by imwyh** [comment]
重新部署works得以解决，但是不清楚是否能够长期解决此问题

**Comment by lovitus** [comment]
不是这些的原因。
是 sub.cmliussss.workers.dev 这个跑挂了

**Comment by cmliu** [comment]
旧的订阅器被打死了，更新代码重新部署就可以恢复了
