### ISSUE TITLE
节点都无法连接了

### ISSUE THREAD

**Issue by hilive** [cmliu/edgetunnel#26]
![WX20240319-135859@2x](https://github.com/cmliu/edgetunnel/assets/52926382/09bf7e04-049b-40e2-9d02-a4e1b5938252)

节点都无法连接了

**Comment by clhlc** [comment]
一样
![Uploading IMG_67498F1B4A0B-1.jpeg…]()

**Comment by hilive** [comment]
应该是歇菜了~~
