### ISSUE TITLE
proxies name requires quotation marks

### ISSUE THREAD

**Issue by marcushsu** [cmliu/edgetunnel#43]
直接將訂閱地址扔給V2RAY及PASSWALL，會造成主機名稱的流水號被濾掉，因此更新訂閱時，清單只會一直增加，不會覆寫。
估計可能是proxy name沒有加引號的關係。

![image](https://github.com/cmliu/edgetunnel/assets/11764515/2cb3b5bf-998b-46a7-be35-8782272cb7b0)

**Comment by cmliu** [comment]
其实是CF获取api的时候的缓存问题,等CF把api的缓存清理了数量就会恢复正常
