### ISSUE TITLE
是不可以用了吗 大佬

### ISSUE THREAD

**Issue by xqd922** [cmliu/edgetunnel#53]
![屏幕截图 2024-04-14 162043](https://github.com/cmliu/edgetunnel/assets/160695918/d39b1a69-67c0-4327-b953-bfdb0cea1694)

**Comment by astraes** [comment]
workers部署显示1101，pages正常。

**Comment by Stanley-baby** [comment]
> workers部署显示1101，pages正常。

是之前部署的还是刚刚部署的？

**Comment by jwyGithub** [comment]
我也是 1101，刚刚部署的

**Comment by xqd922** [comment]
昨天部署的

**Comment by demon869** [comment]
大佬，我也遇到了1101
![image](https://github.com/cmliu/edgetunnel/assets/61615804/0bf58ae7-015c-472a-ac37-88689d341e1f)

**Comment by astraes** [comment]
> > workers部署显示1101，pages正常。
> 
> 是之前部署的还是刚刚部署的？

我是之前部署的今天突然连不上了，重新部署了下就显示1101

**Comment by sunghoppe** [comment]
都这样了，我部署的也是

**Comment by cmliu** [comment]
edgetunnel项目Workers部署的异常情况说明

经过测试，正常代码带上edgetunnel项目部分字段也会触发Error 1101错误，这应该是CF针对edgetunnel项目的一种封堵手段，所以我决定暂不更新修复这个问题的方法（毕竟这算是CF的一种表态，拒绝了edgetunnel项目workers形式的白嫖）。

相信热爱学习up视频的小白朋友也并没有受这次封堵的影响，接下来edgetunnel项目在我这就算翻篇了，开始折腾别的项目~

**Comment by Leefurmore** [comment]
大佬，edgetunnel和vless2sub都部署好了，运行也正常。但有个问题很奇怪，我如果用默认的sub就能带出很多节点信息，但用了自建的加了您的addressapi也订阅不出节点了。除了把sub改成您的地址之外，还有办法能订阅到您的那些节点吗？

> edgetunnel项目Workers部署的异常情况说明
> 
> 经过测试，正常部署edgetunnel项目代码会触发Error 1101错误，这是CF针对edgetunnel项目的一种封堵手段，所以我决定暂不更新修复这个问题的版本（毕竟这算是CF的一种表态，明确拒绝了edgetunnel项目workers形式的白嫖）。
> 
> 相信热爱学习up视频的小白朋友也并没有受这次封堵的影响，接下来edgetunnel项目在我这就算翻篇了，开始折腾别的项目~
