### ISSUE TITLE
如何制作quantumlt X的远程服务器规则？

### ISSUE THREAD

**Issue by bingoku** [cmliu/edgetunnel#61]
如题，quantumlt X 刚更新现在已经支持vless了，不太清楚使用edgetunnel 如何制作

**Comment by cmliu** [comment]
> 如题，quantumlt X 刚更新现在已经支持vless了，不太清楚使用edgetunnel 如何制作

我也不清楚，这个问题你应该问qx啊。不会开车的话应该是去学车，而不是问路

**Comment by firimar** [comment]
> 如题，quantumlt X 刚更新现在已经支持vless了，不太清楚使用edgetunnel 如何制作

用base64的 能被解析器解析出来
