### ISSUE TITLE
订阅的出来的名字 能不能添加前后缀

### ISSUE THREAD

**Issue by securecrt** [cmliu/edgetunnel#83]
对订阅产生的 几十个节点在每个的名字后面或前面 按照 01  02 03 ... 这样添加后缀 或者前缀

**Comment by cmliu** [comment]
> 对订阅产生的 几十个节点在每个的名字后面或前面 按照 01 02 03 ... 这样添加后缀 或者前缀

自己部署优选订阅生成器就可以了
