### ISSUE TITLE
mac上的clashX软件导入订阅地址报错"Remote Config Format Error: proxy 0: unsupport proxy type: vless"

### ISSUE THREAD

**Issue by evilvlso** [cmliu/edgetunnel#95]
请问是为啥捏
我导入的是clash的地址
<img width="253" alt="image" src="https://github.com/cmliu/edgetunnel/assets/25767862/dd197b06-dc82-463a-857a-8c28dbf769d2">

**Comment by evilvlso** [comment]
这个问题通过升级clashX解决了，但是有个新问题
订阅的地址都处于failed的状态无法访问
请问这是为啥呢？

**Comment by ImLTHQ** [comment]
延迟测试链接填http://www.gstatic.com/generate_204
![Uploading bf08b5b0a90fa806996a8b67b85ce5f3.png…]()

**Comment by peasoft** [comment]
换 Meta (mihomo) 内核，原版 Clash 不支持 vless。
